<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * https://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\management\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\management\Entity\SampleConfig;
use Doctrine\Persistence\ManagerRegistry; 

/**
 * Sample Config.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SampleConfigRepository extends AbstractRepository
{
    /**
     * SampleConfigRepository constructor.
     *
     * @param ManagerRegistry $registry
     */
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, SampleConfig::class);
    }

    /**
     * @param int $id
     *
     * @return SampleConfig|null
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }
}