name: CI
on:
  push:
    branches:
      - 'master'
    paths:
      - '**/*.php'
  pull_request:
    branches:
      - 'master'
    paths:
      - '**/*.php'
jobs:
  test:
    name: テスト
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      APP_ENV: dev
      APP_DEBUG: 0

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: 設定コピー
        run: |
          cp phpunit.xml.dist phpunit.xml
          cp .php-cs-fixer.dist.php.dist .php-cs-fixer.dist.php

      - name: コーディング規約チェック
        run: composer run-script validate

      - name: テスト実行
        run: composer run-script test
